// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_BGjhaGH9NQpMhXGlgcvkTmezddEDpVI',
    appId: '1:63274831923:web:fcb6c8a7549410d9141346',
    messagingSenderId: '63274831923',
    projectId: 'locaquest-f9cee',
    authDomain: 'locaquest-f9cee.firebaseapp.com',
    storageBucket: 'locaquest-f9cee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttgU9w-nlR-DTsoRVozGXad7Uv818f4k',
    appId: '1:63274831923:android:753c39c226eeec85141346',
    messagingSenderId: '63274831923',
    projectId: 'locaquest-f9cee',
    storageBucket: 'locaquest-f9cee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWzq-QPKOeSuwAvoPAO7rmJ16G5dG5wi8',
    appId: '1:63274831923:ios:0e56f27c984de52a141346',
    messagingSenderId: '63274831923',
    projectId: 'locaquest-f9cee',
    storageBucket: 'locaquest-f9cee.firebasestorage.app',
    iosBundleId: 'com.example.fluttterLocaquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWzq-QPKOeSuwAvoPAO7rmJ16G5dG5wi8',
    appId: '1:63274831923:ios:0e56f27c984de52a141346',
    messagingSenderId: '63274831923',
    projectId: 'locaquest-f9cee',
    storageBucket: 'locaquest-f9cee.firebasestorage.app',
    iosBundleId: 'com.example.fluttterLocaquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_BGjhaGH9NQpMhXGlgcvkTmezddEDpVI',
    appId: '1:63274831923:web:d083753448ebf3cb141346',
    messagingSenderId: '63274831923',
    projectId: 'locaquest-f9cee',
    authDomain: 'locaquest-f9cee.firebaseapp.com',
    storageBucket: 'locaquest-f9cee.firebasestorage.app',
  );
}
